n = input('Digite qualquer coisa: ')
print('O tipo primitivo dela é ', type(n))
print('Possui apenas espaços?', n.isspace())
print('O que você digitou é numérico?', n.isnumeric())
print('O que você digitou é uma palavra com letras?', n.isalpha())
print('O que você digitou é uma palavra com letras e numeros?', n.isalnum())
print('O que você digitou é uma palavra com todas as letras maiúsculas?', n.isupper())
print('O que você digitou é uma palavra com todas as letras minúsculas?', n.islower())
print('O que você digitou está capitalizado? ', n.istitle())